// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.V1.Channels.Airbnb.Listings.Item.Amenities
{
    /// <summary>
    /// At least one amenity across `amenities` and `accessibility_amenities`. A body that changes nothing is refused rather than reported as a successful write.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AmenitiesPutRequestBody : IParsable
    {
        /// <summary>The accessibility_amenities property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Repull.SDK.V1.Channels.Airbnb.Listings.Item.Amenities.AmenitiesPutRequestBody_accessibility_amenities>? AccessibilityAmenities { get; set; }
#nullable restore
#else
        public List<global::Repull.SDK.V1.Channels.Airbnb.Listings.Item.Amenities.AmenitiesPutRequestBody_accessibility_amenities> AccessibilityAmenities { get; set; }
#endif
        /// <summary>The amenities property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Repull.SDK.V1.Channels.Airbnb.Listings.Item.Amenities.AmenitiesPutRequestBody_amenities>? Amenities { get; set; }
#nullable restore
#else
        public List<global::Repull.SDK.V1.Channels.Airbnb.Listings.Item.Amenities.AmenitiesPutRequestBody_amenities> Amenities { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.V1.Channels.Airbnb.Listings.Item.Amenities.AmenitiesPutRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Repull.SDK.V1.Channels.Airbnb.Listings.Item.Amenities.AmenitiesPutRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.V1.Channels.Airbnb.Listings.Item.Amenities.AmenitiesPutRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accessibility_amenities", n => { AccessibilityAmenities = n.GetCollectionOfObjectValues<global::Repull.SDK.V1.Channels.Airbnb.Listings.Item.Amenities.AmenitiesPutRequestBody_accessibility_amenities>(global::Repull.SDK.V1.Channels.Airbnb.Listings.Item.Amenities.AmenitiesPutRequestBody_accessibility_amenities.CreateFromDiscriminatorValue)?.AsList(); } },
                { "amenities", n => { Amenities = n.GetCollectionOfObjectValues<global::Repull.SDK.V1.Channels.Airbnb.Listings.Item.Amenities.AmenitiesPutRequestBody_amenities>(global::Repull.SDK.V1.Channels.Airbnb.Listings.Item.Amenities.AmenitiesPutRequestBody_amenities.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Repull.SDK.V1.Channels.Airbnb.Listings.Item.Amenities.AmenitiesPutRequestBody_accessibility_amenities>("accessibility_amenities", AccessibilityAmenities);
            writer.WriteCollectionOfObjectValues<global::Repull.SDK.V1.Channels.Airbnb.Listings.Item.Amenities.AmenitiesPutRequestBody_amenities>("amenities", Amenities);
        }
    }
}
#pragma warning restore CS0618
