// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Repull.SDK.V1.Reservations.Item.Decline
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DeclinePostResponse_channel
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "airbnb")]
        #pragma warning disable CS1591
        Airbnb,
        #pragma warning restore CS1591
    }
}
