// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.V1.Connections.Item.Mappings.Automap
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AutomapPostResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The applied property</summary>
        public bool? Applied { get; set; }
        /// <summary>The channel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Channel { get; set; }
#nullable restore
#else
        public string Channel { get; set; }
#endif
        /// <summary>The connection_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConnectionId { get; set; }
#nullable restore
#else
        public string ConnectionId { get; set; }
#endif
        /// <summary>The results property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Repull.SDK.V1.Connections.Item.Mappings.Automap.AutomapPostResponse_results>? Results { get; set; }
#nullable restore
#else
        public List<global::Repull.SDK.V1.Connections.Item.Mappings.Automap.AutomapPostResponse_results> Results { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.V1.Connections.Item.Mappings.Automap.AutomapPostResponse"/> and sets the default values.
        /// </summary>
        public AutomapPostResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.V1.Connections.Item.Mappings.Automap.AutomapPostResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Repull.SDK.V1.Connections.Item.Mappings.Automap.AutomapPostResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.V1.Connections.Item.Mappings.Automap.AutomapPostResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "applied", n => { Applied = n.GetBoolValue(); } },
                { "channel", n => { Channel = n.GetStringValue(); } },
                { "connection_id", n => { ConnectionId = n.GetStringValue(); } },
                { "results", n => { Results = n.GetCollectionOfObjectValues<global::Repull.SDK.V1.Connections.Item.Mappings.Automap.AutomapPostResponse_results>(global::Repull.SDK.V1.Connections.Item.Mappings.Automap.AutomapPostResponse_results.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("applied", Applied);
            writer.WriteStringValue("channel", Channel);
            writer.WriteStringValue("connection_id", ConnectionId);
            writer.WriteCollectionOfObjectValues<global::Repull.SDK.V1.Connections.Item.Mappings.Automap.AutomapPostResponse_results>("results", Results);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
