// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.V1.Connect.Track.Credentials
{
    /// <summary>
    /// The Track domain and an API key + secret.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CredentialsPostRequestBody_credentials : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Track API key.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiKey { get; set; }
#nullable restore
#else
        public string ApiKey { get; set; }
#endif
        /// <summary>Track API secret, shown next to the key in Track.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiSecret { get; set; }
#nullable restore
#else
        public string ApiSecret { get; set; }
#endif
        /// <summary>How requests to Track are signed. Leave the default unless Track support told you otherwise.</summary>
        public global::Repull.SDK.V1.Connect.Track.Credentials.CredentialsPostRequestBody_credentials_authMode? AuthMode { get; set; }
        /// <summary>Your Track domain: `acme.trackhs.com`, or just the subdomain `acme`. A full URL is accepted; only the host is kept.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Domain { get; set; }
#nullable restore
#else
        public string Domain { get; set; }
#endif
        /// <summary>HMAC realm. Defaults to `Acquia`, the realm Track&apos;s HMAC signing uses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HmacRealm { get; set; }
#nullable restore
#else
        public string HmacRealm { get; set; }
#endif
        /// <summary>`server` — a Server Key (Company Setup → API Keys), full access, recommended. `channel` — a Channel Key (PMS Setup → Distribution Channels), booking only.</summary>
        public global::Repull.SDK.V1.Connect.Track.Credentials.CredentialsPostRequestBody_credentials_keyType? KeyType { get; set; }
        /// <summary>The Track move reason used when a reservation is moved to another unit. Without it, unit changes are refused.</summary>
        public int? MoveReasonId { get; set; }
        /// <summary>The Track payment type that payments recorded through this connection are posted to.</summary>
        public int? PaymentTypeId { get; set; }
        /// <summary>Whether `apiSecret` is base64-encoded, as Track issues it. Set false to sign with the secret&apos;s raw text.</summary>
        public bool? SecretIsBase64 { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.V1.Connect.Track.Credentials.CredentialsPostRequestBody_credentials"/> and sets the default values.
        /// </summary>
        public CredentialsPostRequestBody_credentials()
        {
            AdditionalData = new Dictionary<string, object>();
            AuthMode = global::Repull.SDK.V1.Connect.Track.Credentials.CredentialsPostRequestBody_credentials_authMode.Hmac;
            KeyType = global::Repull.SDK.V1.Connect.Track.Credentials.CredentialsPostRequestBody_credentials_keyType.Server;
            SecretIsBase64 = true;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.V1.Connect.Track.Credentials.CredentialsPostRequestBody_credentials"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Repull.SDK.V1.Connect.Track.Credentials.CredentialsPostRequestBody_credentials CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.V1.Connect.Track.Credentials.CredentialsPostRequestBody_credentials();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "apiKey", n => { ApiKey = n.GetStringValue(); } },
                { "apiSecret", n => { ApiSecret = n.GetStringValue(); } },
                { "authMode", n => { AuthMode = n.GetEnumValue<global::Repull.SDK.V1.Connect.Track.Credentials.CredentialsPostRequestBody_credentials_authMode>(); } },
                { "domain", n => { Domain = n.GetStringValue(); } },
                { "hmacRealm", n => { HmacRealm = n.GetStringValue(); } },
                { "keyType", n => { KeyType = n.GetEnumValue<global::Repull.SDK.V1.Connect.Track.Credentials.CredentialsPostRequestBody_credentials_keyType>(); } },
                { "moveReasonId", n => { MoveReasonId = n.GetIntValue(); } },
                { "paymentTypeId", n => { PaymentTypeId = n.GetIntValue(); } },
                { "secretIsBase64", n => { SecretIsBase64 = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("apiKey", ApiKey);
            writer.WriteStringValue("apiSecret", ApiSecret);
            writer.WriteEnumValue<global::Repull.SDK.V1.Connect.Track.Credentials.CredentialsPostRequestBody_credentials_authMode>("authMode", AuthMode);
            writer.WriteStringValue("domain", Domain);
            writer.WriteStringValue("hmacRealm", HmacRealm);
            writer.WriteEnumValue<global::Repull.SDK.V1.Connect.Track.Credentials.CredentialsPostRequestBody_credentials_keyType>("keyType", KeyType);
            writer.WriteIntValue("moveReasonId", MoveReasonId);
            writer.WriteIntValue("paymentTypeId", PaymentTypeId);
            writer.WriteBoolValue("secretIsBase64", SecretIsBase64);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
