// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.Api.Studio.Generate
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GeneratePostResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>True if the response was served from cache.</summary>
        public bool? Cached { get; set; }
        /// <summary>Cost in millionths of a USD.</summary>
        public int? CostUsdMicro { get; set; }
        /// <summary>True if the primary model failed and Repull AI fell back to the secondary.</summary>
        public bool? Fallback { get; set; }
        /// <summary>The generation_id property</summary>
        public Guid? GenerationId { get; set; }
        /// <summary>The latency_ms property</summary>
        public int? LatencyMs { get; set; }
        /// <summary>Model identifier that produced the response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>Generated completion text.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>The tokens_in property</summary>
        public int? TokensIn { get; set; }
        /// <summary>The tokens_out property</summary>
        public int? TokensOut { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.Api.Studio.Generate.GeneratePostResponse_data"/> and sets the default values.
        /// </summary>
        public GeneratePostResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.Api.Studio.Generate.GeneratePostResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Repull.SDK.Api.Studio.Generate.GeneratePostResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.Api.Studio.Generate.GeneratePostResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cached", n => { Cached = n.GetBoolValue(); } },
                { "cost_usd_micro", n => { CostUsdMicro = n.GetIntValue(); } },
                { "fallback", n => { Fallback = n.GetBoolValue(); } },
                { "generation_id", n => { GenerationId = n.GetGuidValue(); } },
                { "latency_ms", n => { LatencyMs = n.GetIntValue(); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "tokens_in", n => { TokensIn = n.GetIntValue(); } },
                { "tokens_out", n => { TokensOut = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("cached", Cached);
            writer.WriteIntValue("cost_usd_micro", CostUsdMicro);
            writer.WriteBoolValue("fallback", Fallback);
            writer.WriteGuidValue("generation_id", GenerationId);
            writer.WriteIntValue("latency_ms", LatencyMs);
            writer.WriteStringValue("model", Model);
            writer.WriteStringValue("text", Text);
            writer.WriteIntValue("tokens_in", TokensIn);
            writer.WriteIntValue("tokens_out", TokensOut);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
