// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.V1.Conversations.Item.PreApproval
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PreApprovalPostResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The blockInstantBooking property</summary>
        public bool? BlockInstantBooking { get; set; }
        /// <summary>The conversationId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConversationId { get; set; }
#nullable restore
#else
        public string ConversationId { get; set; }
#endif
        /// <summary>When the guest can no longer book on the pre-approval, if Airbnb reported it.</summary>
        public DateTimeOffset? ExpiresAt { get; set; }
        /// <summary>The status property</summary>
        public global::Repull.SDK.V1.Conversations.Item.PreApproval.PreApprovalPostResponse_status? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.V1.Conversations.Item.PreApproval.PreApprovalPostResponse"/> and sets the default values.
        /// </summary>
        public PreApprovalPostResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.V1.Conversations.Item.PreApproval.PreApprovalPostResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Repull.SDK.V1.Conversations.Item.PreApproval.PreApprovalPostResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.V1.Conversations.Item.PreApproval.PreApprovalPostResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "blockInstantBooking", n => { BlockInstantBooking = n.GetBoolValue(); } },
                { "conversationId", n => { ConversationId = n.GetStringValue(); } },
                { "expiresAt", n => { ExpiresAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Repull.SDK.V1.Conversations.Item.PreApproval.PreApprovalPostResponse_status>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("blockInstantBooking", BlockInstantBooking);
            writer.WriteStringValue("conversationId", ConversationId);
            writer.WriteDateTimeOffsetValue("expiresAt", ExpiresAt);
            writer.WriteEnumValue<global::Repull.SDK.V1.Conversations.Item.PreApproval.PreApprovalPostResponse_status>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
