// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Repull.SDK.V1.Channels.Booking.Setup
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SetupPostRequestBody_action
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "create-property")]
        #pragma warning disable CS1591
        CreateProperty,
        #pragma warning restore CS1591
        [EnumMember(Value = "add-room")]
        #pragma warning disable CS1591
        AddRoom,
        #pragma warning restore CS1591
        [EnumMember(Value = "add-unit")]
        #pragma warning disable CS1591
        AddUnit,
        #pragma warning restore CS1591
        [EnumMember(Value = "advance")]
        #pragma warning disable CS1591
        Advance,
        #pragma warning restore CS1591
        [EnumMember(Value = "create-legal-entity")]
        #pragma warning disable CS1591
        CreateLegalEntity,
        #pragma warning restore CS1591
        [EnumMember(Value = "check-legal-status")]
        #pragma warning disable CS1591
        CheckLegalStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "check-readiness")]
        #pragma warning disable CS1591
        CheckReadiness,
        #pragma warning restore CS1591
        [EnumMember(Value = "open-property")]
        #pragma warning disable CS1591
        OpenProperty,
        #pragma warning restore CS1591
        [EnumMember(Value = "set-contacts")]
        #pragma warning disable CS1591
        SetContacts,
        #pragma warning restore CS1591
        [EnumMember(Value = "set-policies")]
        #pragma warning disable CS1591
        SetPolicies,
        #pragma warning restore CS1591
    }
}
