// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Repull.SDK.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Repull.SDK.V1.Listings.Status
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\listings\status
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StatusRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.V1.Listings.Status.StatusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatusRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/listings/status", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.V1.Listings.Status.StatusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatusRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/listings/status", rawUrl)
        {
        }
        /// <summary>
        /// Sets up to 500 listings active or inactive in one call. Send `{ &quot;listingIds&quot;: [&quot;4118&quot;, &quot;4119&quot;], &quot;active&quot;: false }` to deactivate them, or `&quot;active&quot;: true` to activate them.An inactive listing is not counted toward your plan&apos;s listing limit or billed. It is NOT deleted and the upstream channel (Airbnb / Booking.com / your PMS) is never touched — its data keeps syncing, so it is complete the moment you activate it again. Until then it cannot be read, changed, or receive webhooks.**All or nothing.** Nothing changes unless the whole request can be applied:- If any id is not one of your listings, the call returns `404` naming those ids.- If activating would take you over your plan&apos;s listing limit, the call returns `402 listings_limit_exceeded`. Only listings that are currently inactive count toward the new total, so re-sending ids that are already active never trips the limit.Deactivating is always allowed, including when your account is already over its limit — it is how you get back under it.**Idempotent.** Ids already in the requested state are returned in `unchanged`; ids this call changed are returned in `updated`.For a single listing, `PATCH /v1/listings/{id}` does the same.
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.Models.ListingStatusBatchResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Repull.SDK.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Repull.SDK.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Repull.SDK.Models.Error">When receiving a 402 status code</exception>
        /// <exception cref="global::Repull.SDK.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Repull.SDK.Models.Error">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Repull.SDK.Models.ListingStatusBatchResponse?> PostAsync(global::Repull.SDK.Models.ListingStatusBatchRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Repull.SDK.Models.ListingStatusBatchResponse> PostAsync(global::Repull.SDK.Models.ListingStatusBatchRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Repull.SDK.Models.Error.CreateFromDiscriminatorValue },
                { "401", global::Repull.SDK.Models.Error.CreateFromDiscriminatorValue },
                { "402", global::Repull.SDK.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::Repull.SDK.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::Repull.SDK.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Repull.SDK.Models.ListingStatusBatchResponse>(requestInfo, global::Repull.SDK.Models.ListingStatusBatchResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Sets up to 500 listings active or inactive in one call. Send `{ &quot;listingIds&quot;: [&quot;4118&quot;, &quot;4119&quot;], &quot;active&quot;: false }` to deactivate them, or `&quot;active&quot;: true` to activate them.An inactive listing is not counted toward your plan&apos;s listing limit or billed. It is NOT deleted and the upstream channel (Airbnb / Booking.com / your PMS) is never touched — its data keeps syncing, so it is complete the moment you activate it again. Until then it cannot be read, changed, or receive webhooks.**All or nothing.** Nothing changes unless the whole request can be applied:- If any id is not one of your listings, the call returns `404` naming those ids.- If activating would take you over your plan&apos;s listing limit, the call returns `402 listings_limit_exceeded`. Only listings that are currently inactive count toward the new total, so re-sending ids that are already active never trips the limit.Deactivating is always allowed, including when your account is already over its limit — it is how you get back under it.**Idempotent.** Ids already in the requested state are returned in `unchanged`; ids this call changed are returned in `updated`.For a single listing, `PATCH /v1/listings/{id}` does the same.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Repull.SDK.Models.ListingStatusBatchRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Repull.SDK.Models.ListingStatusBatchRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.V1.Listings.Status.StatusRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Repull.SDK.V1.Listings.Status.StatusRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Repull.SDK.V1.Listings.Status.StatusRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class StatusRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
