// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Repull.SDK.V1.Connect.Igms.Credentials;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Repull.SDK.V1.Connect.Igms
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\connect\igms
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IgmsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The credentials property</summary>
        public global::Repull.SDK.V1.Connect.Igms.Credentials.CredentialsRequestBuilder Credentials
        {
            get => new global::Repull.SDK.V1.Connect.Igms.Credentials.CredentialsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.V1.Connect.Igms.IgmsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IgmsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/connect/igms", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.V1.Connect.Igms.IgmsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IgmsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/connect/igms", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
