// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Repull.SDK.V1.Reviews
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetReviewer_roleQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "guest")]
        #pragma warning disable CS1591
        Guest,
        #pragma warning restore CS1591
        [EnumMember(Value = "host")]
        #pragma warning disable CS1591
        Host,
        #pragma warning restore CS1591
        [EnumMember(Value = "all")]
        #pragma warning disable CS1591
        All,
        #pragma warning restore CS1591
    }
}
