// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.V1.Channels.Airbnb.Transactions
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TransactionsPostResponse_accounts : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Airbnb host id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountId { get; set; }
#nullable restore
#else
        public string AccountId { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The count property</summary>
        public int? Count { get; set; }
        /// <summary>Present only when this account was not refreshed. `code` is `connection_reauth_required`, `airbnb_rejected`, `airbnb_rate_limited`, `airbnb_error`, or `time_budget` (the request ran out of time before reaching it: refresh it alone with `?account_id=`).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Repull.SDK.V1.Channels.Airbnb.Transactions.TransactionsPostResponse_accounts_error? Error { get; set; }
#nullable restore
#else
        public global::Repull.SDK.V1.Channels.Airbnb.Transactions.TransactionsPostResponse_accounts_error Error { get; set; }
#endif
        /// <summary>Payouts in the refreshed window.</summary>
        public int? Payouts { get; set; }
        /// <summary>UPCOMING lines Airbnb no longer lists (paid out or cancelled) and were removed.</summary>
        public int? UpcomingRemoved { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.V1.Channels.Airbnb.Transactions.TransactionsPostResponse_accounts"/> and sets the default values.
        /// </summary>
        public TransactionsPostResponse_accounts()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.V1.Channels.Airbnb.Transactions.TransactionsPostResponse_accounts"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Repull.SDK.V1.Channels.Airbnb.Transactions.TransactionsPostResponse_accounts CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.V1.Channels.Airbnb.Transactions.TransactionsPostResponse_accounts();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountId", n => { AccountId = n.GetStringValue(); } },
                { "count", n => { Count = n.GetIntValue(); } },
                { "error", n => { Error = n.GetObjectValue<global::Repull.SDK.V1.Channels.Airbnb.Transactions.TransactionsPostResponse_accounts_error>(global::Repull.SDK.V1.Channels.Airbnb.Transactions.TransactionsPostResponse_accounts_error.CreateFromDiscriminatorValue); } },
                { "payouts", n => { Payouts = n.GetIntValue(); } },
                { "upcomingRemoved", n => { UpcomingRemoved = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accountId", AccountId);
            writer.WriteIntValue("count", Count);
            writer.WriteObjectValue<global::Repull.SDK.V1.Channels.Airbnb.Transactions.TransactionsPostResponse_accounts_error>("error", Error);
            writer.WriteIntValue("payouts", Payouts);
            writer.WriteIntValue("upcomingRemoved", UpcomingRemoved);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
