// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Repull.SDK.V1.Conversations.Item.SpecialOffers.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WithOfferDeleteResponse_status
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "withdrawn")]
        #pragma warning disable CS1591
        Withdrawn,
        #pragma warning restore CS1591
    }
}
