// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Repull.SDK.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Repull.SDK.V1.Channels.Plumguide.Bookings
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\channels\plumguide\bookings
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BookingsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.V1.Channels.Plumguide.Bookings.BookingsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BookingsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/channels/plumguide/bookings{?booking_code*,listing_id*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.V1.Channels.Plumguide.Bookings.BookingsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BookingsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/channels/plumguide/bookings{?booking_code*,listing_id*}", rawUrl)
        {
        }
        /// <summary>
        /// List Plumguide bookings. Default returns all bookings; pass `listing_id` to filter to one listing, or `booking_code` to fetch a single booking.Returns `403 listing_inactive` when `listing_id` or `booking_code` resolves to an inactive listing. The unfiltered list is read straight from Plum Guide and is not filtered by listing status.
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Repull.SDK.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Repull.SDK.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Repull.SDK.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Repull.SDK.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> GetAsync(Action<RequestConfiguration<global::Repull.SDK.V1.Channels.Plumguide.Bookings.BookingsRequestBuilder.BookingsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> GetAsync(Action<RequestConfiguration<global::Repull.SDK.V1.Channels.Plumguide.Bookings.BookingsRequestBuilder.BookingsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Repull.SDK.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::Repull.SDK.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::Repull.SDK.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::Repull.SDK.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List Plumguide bookings. Default returns all bookings; pass `listing_id` to filter to one listing, or `booking_code` to fetch a single booking.Returns `403 listing_inactive` when `listing_id` or `booking_code` resolves to an inactive listing. The unfiltered list is read straight from Plum Guide and is not filtered by listing status.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Repull.SDK.V1.Channels.Plumguide.Bookings.BookingsRequestBuilder.BookingsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Repull.SDK.V1.Channels.Plumguide.Bookings.BookingsRequestBuilder.BookingsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.V1.Channels.Plumguide.Bookings.BookingsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Repull.SDK.V1.Channels.Plumguide.Bookings.BookingsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Repull.SDK.V1.Channels.Plumguide.Bookings.BookingsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List Plumguide bookings. Default returns all bookings; pass `listing_id` to filter to one listing, or `booking_code` to fetch a single booking.Returns `403 listing_inactive` when `listing_id` or `booking_code` resolves to an inactive listing. The unfiltered list is read straight from Plum Guide and is not filtered by listing status.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BookingsRequestBuilderGetQueryParameters 
        {
            /// <summary>Fetch a single booking by its Plumguide booking code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("booking_code")]
            public string? BookingCode { get; set; }
#nullable restore
#else
            [QueryParameter("booking_code")]
            public string BookingCode { get; set; }
#endif
            /// <summary>Filter to a single Plumguide listing.</summary>
            [QueryParameter("listing_id")]
            public int? ListingId { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BookingsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Repull.SDK.V1.Channels.Plumguide.Bookings.BookingsRequestBuilder.BookingsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
