// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Repull.SDK.V1.Channels.Airbnb.Listings.Item.BookingSettings
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BookingSettingsPutRequestBody_instantBook_guestCategory
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "everyone")]
        #pragma warning disable CS1591
        Everyone,
        #pragma warning restore CS1591
        [EnumMember(Value = "experienced_guests_only")]
        #pragma warning disable CS1591
        Experienced_guests_only,
        #pragma warning restore CS1591
        [EnumMember(Value = "recommended_guests_only")]
        #pragma warning disable CS1591
        Recommended_guests_only,
        #pragma warning restore CS1591
        [EnumMember(Value = "off")]
        #pragma warning disable CS1591
        Off,
        #pragma warning restore CS1591
    }
}
