// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.V1.Channels.Airbnb.Listings.Item.CheckoutGuide
{
    [Obsolete("This class is obsolete. Use CheckoutGuideGetResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CheckoutGuideResponse : global::Repull.SDK.V1.Channels.Airbnb.Listings.Item.CheckoutGuide.CheckoutGuideGetResponse, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.V1.Channels.Airbnb.Listings.Item.CheckoutGuide.CheckoutGuideResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Repull.SDK.V1.Channels.Airbnb.Listings.Item.CheckoutGuide.CheckoutGuideResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.V1.Channels.Airbnb.Listings.Item.CheckoutGuide.CheckoutGuideResponse();
        }
    }
}
#pragma warning restore CS0618
