// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.Models
{
    /// <summary>
    /// Workspace-level Airbnb connection state. The dedicated answer to &quot;is my Airbnb still connected?&quot; — emit one summary instead of inferring from per-listing 401s.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AirbnbConnectionSummary : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Self-serve recovery URL. Set whenever `status` is anything other than `connected`. Points at the dashboard surface where the host re-authorizes (or initiates the first OAuth flow for `never_connected` workspaces).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FixUrl { get; set; }
#nullable restore
#else
        public string FixUrl { get; set; }
#endif
        /// <summary>The hostCount property</summary>
        public int? HostCount { get; set; }
        /// <summary>The hosts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Repull.SDK.Models.AirbnbConnectionHost>? Hosts { get; set; }
#nullable restore
#else
        public List<global::Repull.SDK.Models.AirbnbConnectionHost> Hosts { get; set; }
#endif
        /// <summary>`connected` — every host is currently connected. `reconnect_required` — at least one host is connected, at least one is not. `disconnected` — every host has been disconnected. `never_connected` — the workspace has never linked an Airbnb account.</summary>
        public global::Repull.SDK.Models.AirbnbConnectionSummary_status? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.Models.AirbnbConnectionSummary"/> and sets the default values.
        /// </summary>
        public AirbnbConnectionSummary()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.Models.AirbnbConnectionSummary"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Repull.SDK.Models.AirbnbConnectionSummary CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.Models.AirbnbConnectionSummary();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "fixUrl", n => { FixUrl = n.GetStringValue(); } },
                { "hostCount", n => { HostCount = n.GetIntValue(); } },
                { "hosts", n => { Hosts = n.GetCollectionOfObjectValues<global::Repull.SDK.Models.AirbnbConnectionHost>(global::Repull.SDK.Models.AirbnbConnectionHost.CreateFromDiscriminatorValue)?.AsList(); } },
                { "status", n => { Status = n.GetEnumValue<global::Repull.SDK.Models.AirbnbConnectionSummary_status>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("fixUrl", FixUrl);
            writer.WriteIntValue("hostCount", HostCount);
            writer.WriteCollectionOfObjectValues<global::Repull.SDK.Models.AirbnbConnectionHost>("hosts", Hosts);
            writer.WriteEnumValue<global::Repull.SDK.Models.AirbnbConnectionSummary_status>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
