// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AirbnbPermitsWriteRequest_permits : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Keyed by each question&apos;s `answer_key`. Each value carries exactly one field, chosen by the question&apos;s `type`: TEXT → `text_value`, ATTESTATION → `attestation_value`, RADIO → `radio_value`, DATE → `date_value`, SELECT → `selected_options_value`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Repull.SDK.Models.AirbnbPermitsWriteRequest_permits_answers? Answers { get; set; }
#nullable restore
#else
        public global::Repull.SDK.Models.AirbnbPermitsWriteRequest_permits_answers Answers { get; set; }
#endif
        /// <summary>The `slug` of the flow you are answering, e.g. `existing_registration` or `exemption_claim`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FlowSlug { get; set; }
#nullable restore
#else
        public string FlowSlug { get; set; }
#endif
        /// <summary>Echo the GET&apos;s `regulation_context` (e.g. `initial`) when present.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RegulationContext { get; set; }
#nullable restore
#else
        public string RegulationContext { get; set; }
#endif
        /// <summary>As returned by the GET.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RegulationType { get; set; }
#nullable restore
#else
        public string RegulationType { get; set; }
#endif
        /// <summary>As returned by the GET, e.g. `maui_county_hawaii`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RegulatoryBody { get; set; }
#nullable restore
#else
        public string RegulatoryBody { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.Models.AirbnbPermitsWriteRequest_permits"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Repull.SDK.Models.AirbnbPermitsWriteRequest_permits CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.Models.AirbnbPermitsWriteRequest_permits();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "answers", n => { Answers = n.GetObjectValue<global::Repull.SDK.Models.AirbnbPermitsWriteRequest_permits_answers>(global::Repull.SDK.Models.AirbnbPermitsWriteRequest_permits_answers.CreateFromDiscriminatorValue); } },
                { "flow_slug", n => { FlowSlug = n.GetStringValue(); } },
                { "regulation_context", n => { RegulationContext = n.GetStringValue(); } },
                { "regulation_type", n => { RegulationType = n.GetStringValue(); } },
                { "regulatory_body", n => { RegulatoryBody = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Repull.SDK.Models.AirbnbPermitsWriteRequest_permits_answers>("answers", Answers);
            writer.WriteStringValue("flow_slug", FlowSlug);
            writer.WriteStringValue("regulation_context", RegulationContext);
            writer.WriteStringValue("regulation_type", RegulationType);
            writer.WriteStringValue("regulatory_body", RegulatoryBody);
        }
    }
}
#pragma warning restore CS0618
