// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.Models
{
    /// <summary>
    /// Body for `PUT /v1/channels/airbnb/listings/{id}/pricing`. The `type` discriminator selects the pricing sub-resource. `type: &quot;calendar&quot;` shares the same per-date restriction shape as the availability endpoint (min/max nights, closed-to-arrival/departure, stop-sell via `availability: &quot;unavailable&quot;`).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AirbnbPricingWriteRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Required for `type: &quot;currency&quot;` — ISO 4217 code in capitals, e.g. `USD`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>With `type: &quot;fees&quot;` — the fee changes to apply. **Merged by `fee_type`**: fees you do not mention are kept, the ones you send are set, and `amount: null` removes that fee. (Airbnb itself replaces the whole fee list on every write, so Repull reads the listing&apos;s current fees, applies your changes and writes the full set.) The response is the listing&apos;s fees as Airbnb holds them afterwards.**Units — the same as `GET …/pricing` returns:** a `flat` fee is the amount in the listing currency × 1,000,000 (`160000000` = 160.00); a `percent` fee is a whole percent of the rent (`10` = 10%).Example — add a 10% management fee and keep everything else: `{&quot;type&quot;:&quot;fees&quot;,&quot;fees&quot;:[{&quot;fee_type&quot;:&quot;PASS_THROUGH_MANAGEMENT_FEE&quot;,&quot;amount&quot;:10,&quot;amount_type&quot;:&quot;percent&quot;}]}`. Remove the pet fee: `{&quot;type&quot;:&quot;fees&quot;,&quot;fees&quot;:[{&quot;fee_type&quot;:&quot;PASS_THROUGH_PET_FEE&quot;,&quot;amount&quot;:null}]}`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Repull.SDK.Models.AirbnbPricingWriteRequest_fees>? Fees { get; set; }
#nullable restore
#else
        public List<global::Repull.SDK.Models.AirbnbPricingWriteRequest_fees> Fees { get; set; }
#endif
        /// <summary>Required when `type: &quot;model&quot;` — the pricing-availability model to switch the listing to.</summary>
        public global::Repull.SDK.Models.AirbnbPricingWriteRequest_modelType? ModelType { get; set; }
        /// <summary>Required when `type: &quot;calendar&quot;`. Batch of per-date price + restriction operations.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Repull.SDK.Models.AirbnbCalendarOperation>? Operations { get; set; }
#nullable restore
#else
        public List<global::Repull.SDK.Models.AirbnbCalendarOperation> Operations { get; set; }
#endif
        /// <summary>Required for `type: &quot;los&quot;` — length-of-stay records.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Repull.SDK.Models.AirbnbPricingWriteRequest_records>? Records { get; set; }
#nullable restore
#else
        public List<global::Repull.SDK.Models.AirbnbPricingWriteRequest_records> Records { get; set; }
#endif
        /// <summary>Required for `type: &quot;rule&quot;` — a single pricing rule appended to the listing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Repull.SDK.Models.AirbnbPricingWriteRequest_rule? Rule { get; set; }
#nullable restore
#else
        public global::Repull.SDK.Models.AirbnbPricingWriteRequest_rule Rule { get; set; }
#endif
        /// <summary>Required for `type: &quot;standard&quot; | &quot;rate-plan&quot;` — the pricing-settings object to PUT. With `type: &quot;fees&quot;` it is the raw alternative to `fees`: `{&quot;standard_fees&quot;: [...]}` **replaces every fee** on the listing (Airbnb does not merge), so send the complete list. Prefer `fees`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Repull.SDK.Models.AirbnbPricingWriteRequest_settings? Settings { get; set; }
#nullable restore
#else
        public global::Repull.SDK.Models.AirbnbPricingWriteRequest_settings Settings { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Repull.SDK.Models.AirbnbPricingWriteRequest_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.Models.AirbnbPricingWriteRequest"/> and sets the default values.
        /// </summary>
        public AirbnbPricingWriteRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.Models.AirbnbPricingWriteRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Repull.SDK.Models.AirbnbPricingWriteRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.Models.AirbnbPricingWriteRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "fees", n => { Fees = n.GetCollectionOfObjectValues<global::Repull.SDK.Models.AirbnbPricingWriteRequest_fees>(global::Repull.SDK.Models.AirbnbPricingWriteRequest_fees.CreateFromDiscriminatorValue)?.AsList(); } },
                { "modelType", n => { ModelType = n.GetEnumValue<global::Repull.SDK.Models.AirbnbPricingWriteRequest_modelType>(); } },
                { "operations", n => { Operations = n.GetCollectionOfObjectValues<global::Repull.SDK.Models.AirbnbCalendarOperation>(global::Repull.SDK.Models.AirbnbCalendarOperation.CreateFromDiscriminatorValue)?.AsList(); } },
                { "records", n => { Records = n.GetCollectionOfObjectValues<global::Repull.SDK.Models.AirbnbPricingWriteRequest_records>(global::Repull.SDK.Models.AirbnbPricingWriteRequest_records.CreateFromDiscriminatorValue)?.AsList(); } },
                { "rule", n => { Rule = n.GetObjectValue<global::Repull.SDK.Models.AirbnbPricingWriteRequest_rule>(global::Repull.SDK.Models.AirbnbPricingWriteRequest_rule.CreateFromDiscriminatorValue); } },
                { "settings", n => { Settings = n.GetObjectValue<global::Repull.SDK.Models.AirbnbPricingWriteRequest_settings>(global::Repull.SDK.Models.AirbnbPricingWriteRequest_settings.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Repull.SDK.Models.AirbnbPricingWriteRequest_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("currency", Currency);
            writer.WriteCollectionOfObjectValues<global::Repull.SDK.Models.AirbnbPricingWriteRequest_fees>("fees", Fees);
            writer.WriteEnumValue<global::Repull.SDK.Models.AirbnbPricingWriteRequest_modelType>("modelType", ModelType);
            writer.WriteCollectionOfObjectValues<global::Repull.SDK.Models.AirbnbCalendarOperation>("operations", Operations);
            writer.WriteCollectionOfObjectValues<global::Repull.SDK.Models.AirbnbPricingWriteRequest_records>("records", Records);
            writer.WriteObjectValue<global::Repull.SDK.Models.AirbnbPricingWriteRequest_rule>("rule", Rule);
            writer.WriteObjectValue<global::Repull.SDK.Models.AirbnbPricingWriteRequest_settings>("settings", Settings);
            writer.WriteEnumValue<global::Repull.SDK.Models.AirbnbPricingWriteRequest_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
