// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.Models
{
    /// <summary>
    /// A MERGE, not a replacement: Airbnb keeps one value per disclosure type, a type you leave out keeps the value it has, and to retract a disclosure you send it with `value: false`. A full replacement would let a partial request silently un-declare a security camera — which is a guest-safety statement, not a preference.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AirbnbSafetyDisclosuresWriteRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The disclosures property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Repull.SDK.Models.AirbnbSafetyDisclosure>? Disclosures { get; set; }
#nullable restore
#else
        public List<global::Repull.SDK.Models.AirbnbSafetyDisclosure> Disclosures { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.Models.AirbnbSafetyDisclosuresWriteRequest"/> and sets the default values.
        /// </summary>
        public AirbnbSafetyDisclosuresWriteRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.Models.AirbnbSafetyDisclosuresWriteRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Repull.SDK.Models.AirbnbSafetyDisclosuresWriteRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.Models.AirbnbSafetyDisclosuresWriteRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "disclosures", n => { Disclosures = n.GetCollectionOfObjectValues<global::Repull.SDK.Models.AirbnbSafetyDisclosure>(global::Repull.SDK.Models.AirbnbSafetyDisclosure.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Repull.SDK.Models.AirbnbSafetyDisclosure>("disclosures", Disclosures);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
