// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.Models
{
    /// <summary>
    /// One calendar operation. Supply either `start_date` + `end_date` OR a `dates` array. Every restriction here is forwarded verbatim to Airbnb&apos;s batch calendar API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AirbnbCalendarOperation : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Stop-sell is expressed here: `unavailable` blocks the date(s); `available` re-opens; `default` reverts to rule-based availability.</summary>
        public global::Repull.SDK.Models.AirbnbCalendarOperation_availability? Availability { get; set; }
        /// <summary>Closed-to-arrival — no check-ins on the affected date(s).</summary>
        public bool? ClosedToArrival { get; set; }
        /// <summary>Closed-to-departure — no check-outs on the affected date(s).</summary>
        public bool? ClosedToDeparture { get; set; }
        /// <summary>Nightly price override.</summary>
        public double? DailyPrice { get; set; }
        /// <summary>Explicit date or `start:end` range strings, as an alternative to `start_date`/`end_date`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Dates { get; set; }
#nullable restore
#else
        public List<string> Dates { get; set; }
#endif
        /// <summary>Inclusive range end (pair with `start_date`).</summary>
        public Date? EndDate { get; set; }
        /// <summary>Maximum length of stay for the date(s).</summary>
        public int? MaxNights { get; set; }
        /// <summary>Minimum length of stay for the date(s).</summary>
        public int? MinNights { get; set; }
        /// <summary>The notes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>Inclusive range start (pair with `end_date`).</summary>
        public Date? StartDate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.Models.AirbnbCalendarOperation"/> and sets the default values.
        /// </summary>
        public AirbnbCalendarOperation()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.Models.AirbnbCalendarOperation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Repull.SDK.Models.AirbnbCalendarOperation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.Models.AirbnbCalendarOperation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "availability", n => { Availability = n.GetEnumValue<global::Repull.SDK.Models.AirbnbCalendarOperation_availability>(); } },
                { "closed_to_arrival", n => { ClosedToArrival = n.GetBoolValue(); } },
                { "closed_to_departure", n => { ClosedToDeparture = n.GetBoolValue(); } },
                { "daily_price", n => { DailyPrice = n.GetDoubleValue(); } },
                { "dates", n => { Dates = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "end_date", n => { EndDate = n.GetDateValue(); } },
                { "max_nights", n => { MaxNights = n.GetIntValue(); } },
                { "min_nights", n => { MinNights = n.GetIntValue(); } },
                { "notes", n => { Notes = n.GetStringValue(); } },
                { "start_date", n => { StartDate = n.GetDateValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Repull.SDK.Models.AirbnbCalendarOperation_availability>("availability", Availability);
            writer.WriteBoolValue("closed_to_arrival", ClosedToArrival);
            writer.WriteBoolValue("closed_to_departure", ClosedToDeparture);
            writer.WriteDoubleValue("daily_price", DailyPrice);
            writer.WriteCollectionOfPrimitiveValues<string>("dates", Dates);
            writer.WriteDateValue("end_date", EndDate);
            writer.WriteIntValue("max_nights", MaxNights);
            writer.WriteIntValue("min_nights", MinNights);
            writer.WriteStringValue("notes", Notes);
            writer.WriteDateValue("start_date", StartDate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
