// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Repull.SDK.Models
{
    /// <summary>Transaction kind.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AirbnbTransaction_type
    {
        [EnumMember(Value = "Reservation")]
        #pragma warning disable CS1591
        Reservation,
        #pragma warning restore CS1591
        [EnumMember(Value = "Payout")]
        #pragma warning disable CS1591
        Payout,
        #pragma warning restore CS1591
        [EnumMember(Value = "Resolution_Adjustment")]
        #pragma warning disable CS1591
        Resolution_Adjustment,
        #pragma warning restore CS1591
    }
}
