// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.Models
{
    /// <summary>
    /// A publish is not one call to Airbnb: it is up to eight independent ones (details, description, amenities, rooms, policies, photos, pricing, checkout_tasks), each of which can fail on its own. A PARTIAL publish is normal — what succeeded stays applied; there is no rollback.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AirbnbPublishResult : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Per-section failures. Empty when `published` is true.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Repull.SDK.Models.PublishSectionError>? Errors { get; set; }
#nullable restore
#else
        public List<global::Repull.SDK.Models.PublishSectionError> Errors { get; set; }
#endif
        /// <summary>Fields Airbnb will not let this listing change — collected from the failures above and from the `locked_attributes` Airbnb recorded for the listing. Sending them again returns success and changes nothing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? LockedFields { get; set; }
#nullable restore
#else
        public List<string> LockedFields { get; set; }
#endif
        /// <summary>True only when EVERY attempted section reached Airbnb.</summary>
        public bool? Published { get; set; }
        /// <summary>Set when the publish never started at all (no connection, address missing, subscription gate).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reason { get; set; }
#nullable restore
#else
        public string Reason { get; set; }
#endif
        /// <summary>Sections that landed on Airbnb.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Sections { get; set; }
#nullable restore
#else
        public List<string> Sections { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.Models.AirbnbPublishResult"/> and sets the default values.
        /// </summary>
        public AirbnbPublishResult()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.Models.AirbnbPublishResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Repull.SDK.Models.AirbnbPublishResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.Models.AirbnbPublishResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "errors", n => { Errors = n.GetCollectionOfObjectValues<global::Repull.SDK.Models.PublishSectionError>(global::Repull.SDK.Models.PublishSectionError.CreateFromDiscriminatorValue)?.AsList(); } },
                { "lockedFields", n => { LockedFields = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "published", n => { Published = n.GetBoolValue(); } },
                { "reason", n => { Reason = n.GetStringValue(); } },
                { "sections", n => { Sections = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Repull.SDK.Models.PublishSectionError>("errors", Errors);
            writer.WriteCollectionOfPrimitiveValues<string>("lockedFields", LockedFields);
            writer.WriteBoolValue("published", Published);
            writer.WriteStringValue("reason", Reason);
            writer.WriteCollectionOfPrimitiveValues<string>("sections", Sections);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
