// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Repull.SDK.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AirbnbPricingWriteRequest_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "model")]
        #pragma warning disable CS1591
        Model,
        #pragma warning restore CS1591
        [EnumMember(Value = "standard")]
        #pragma warning disable CS1591
        Standard,
        #pragma warning restore CS1591
        [EnumMember(Value = "los")]
        #pragma warning disable CS1591
        Los,
        #pragma warning restore CS1591
        [EnumMember(Value = "rate-plan")]
        #pragma warning disable CS1591
        RatePlan,
        #pragma warning restore CS1591
        [EnumMember(Value = "fees")]
        #pragma warning disable CS1591
        Fees,
        #pragma warning restore CS1591
        [EnumMember(Value = "currency")]
        #pragma warning disable CS1591
        Currency,
        #pragma warning restore CS1591
        [EnumMember(Value = "rule")]
        #pragma warning disable CS1591
        Rule,
        #pragma warning restore CS1591
        [EnumMember(Value = "calendar")]
        #pragma warning disable CS1591
        Calendar,
        #pragma warning restore CS1591
    }
}
