// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.Models
{
    /// <summary>
    /// Result of `unlist` / `relist`. Reports the state of the LIVE Airbnb listing. The Repull record&apos;s own `active` flag is untouched by both and is deliberately not echoed here, so the two ideas cannot be read as one field.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AirbnbListingLifecycleResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>The action property</summary>
        public global::Repull.SDK.Models.AirbnbListingLifecycleResponse_action? Action { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The airbnbConnectionId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AirbnbConnectionId { get; set; }
#nullable restore
#else
        public string AirbnbConnectionId { get; set; }
#endif
        /// <summary>The channel property</summary>
        public global::Repull.SDK.Models.AirbnbListingLifecycleResponse_channel? Channel { get; set; }
        /// <summary>Repull listing id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Whether the Airbnb listing is taking bookings after this call. `false` after `unlist`, `true` after `relist`.</summary>
        public bool? Live { get; set; }
        /// <summary>True when the result was confirmed by reading the listing back from Airbnb (done on `unlist`: Airbnb accepting the call is not proof the listing came down).</summary>
        public bool? Verified { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.Models.AirbnbListingLifecycleResponse"/> and sets the default values.
        /// </summary>
        public AirbnbListingLifecycleResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.Models.AirbnbListingLifecycleResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Repull.SDK.Models.AirbnbListingLifecycleResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.Models.AirbnbListingLifecycleResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetEnumValue<global::Repull.SDK.Models.AirbnbListingLifecycleResponse_action>(); } },
                { "airbnbConnectionId", n => { AirbnbConnectionId = n.GetStringValue(); } },
                { "channel", n => { Channel = n.GetEnumValue<global::Repull.SDK.Models.AirbnbListingLifecycleResponse_channel>(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "live", n => { Live = n.GetBoolValue(); } },
                { "verified", n => { Verified = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Repull.SDK.Models.AirbnbListingLifecycleResponse_action>("action", Action);
            writer.WriteStringValue("airbnbConnectionId", AirbnbConnectionId);
            writer.WriteEnumValue<global::Repull.SDK.Models.AirbnbListingLifecycleResponse_channel>("channel", Channel);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("live", Live);
            writer.WriteBoolValue("verified", Verified);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
