// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Repull.SDK.Models
{
    /// <summary>What is known about the amounts. Same vocabulary as the top-level `applied`, for this half alone.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BookingRateWritePriceHalf_applied
    {
        [EnumMember(Value = "verified")]
        #pragma warning disable CS1591
        Verified,
        #pragma warning restore CS1591
        [EnumMember(Value = "mismatch")]
        #pragma warning disable CS1591
        Mismatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "rejected")]
        #pragma warning disable CS1591
        Rejected,
        #pragma warning restore CS1591
        [EnumMember(Value = "unverified")]
        #pragma warning disable CS1591
        Unverified,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_requested")]
        #pragma warning disable CS1591
        Not_requested,
        #pragma warning restore CS1591
    }
}
