// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.Models
{
    /// <summary>
    /// Optional length-of-stay / availability restrictions for one rate update. Every field here is forwarded verbatim into Booking.com&apos;s rates XML (`minimumstay`, `maximumstay`, `closedonarrival`, `closedondeparture`, …) — omit a field to leave that restriction untouched.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BookingPricingRateUpdateRestrictions : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Closed-to-arrival — guests may not check in on the affected dates (`closedonarrival`).</summary>
        public bool? ClosedToArrival { get; set; }
        /// <summary>Closed-to-departure — guests may not check out on the affected dates (`closedondeparture`).</summary>
        public bool? ClosedToDeparture { get; set; }
        /// <summary>Arrival-based exact length of stay (`exactstay_arrival`).</summary>
        public int? ExactStayArrival { get; set; }
        /// <summary>Maximum advance-reservation window, format `XDY` (X days Y hours) — `max_advance_res`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MaxAdvanceRes { get; set; }
#nullable restore
#else
        public string MaxAdvanceRes { get; set; }
#endif
        /// <summary>Maximum length of stay (`maximumstay`).</summary>
        public int? MaxStay { get; set; }
        /// <summary>Arrival-based maximum length of stay (`maximumstay_arrival`).</summary>
        public int? MaxStayArrival { get; set; }
        /// <summary>Minimum advance-reservation window, format `XDY` (X days Y hours) — `min_advance_res`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MinAdvanceRes { get; set; }
#nullable restore
#else
        public string MinAdvanceRes { get; set; }
#endif
        /// <summary>Minimum length of stay (`minimumstay`).</summary>
        public int? MinStay { get; set; }
        /// <summary>Arrival-based minimum length of stay (`minimumstay_arrival`).</summary>
        public int? MinStayArrival { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.Models.BookingPricingRateUpdateRestrictions"/> and sets the default values.
        /// </summary>
        public BookingPricingRateUpdateRestrictions()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.Models.BookingPricingRateUpdateRestrictions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Repull.SDK.Models.BookingPricingRateUpdateRestrictions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.Models.BookingPricingRateUpdateRestrictions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "closedToArrival", n => { ClosedToArrival = n.GetBoolValue(); } },
                { "closedToDeparture", n => { ClosedToDeparture = n.GetBoolValue(); } },
                { "exactStayArrival", n => { ExactStayArrival = n.GetIntValue(); } },
                { "maxAdvanceRes", n => { MaxAdvanceRes = n.GetStringValue(); } },
                { "maxStay", n => { MaxStay = n.GetIntValue(); } },
                { "maxStayArrival", n => { MaxStayArrival = n.GetIntValue(); } },
                { "minAdvanceRes", n => { MinAdvanceRes = n.GetStringValue(); } },
                { "minStay", n => { MinStay = n.GetIntValue(); } },
                { "minStayArrival", n => { MinStayArrival = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("closedToArrival", ClosedToArrival);
            writer.WriteBoolValue("closedToDeparture", ClosedToDeparture);
            writer.WriteIntValue("exactStayArrival", ExactStayArrival);
            writer.WriteStringValue("maxAdvanceRes", MaxAdvanceRes);
            writer.WriteIntValue("maxStay", MaxStay);
            writer.WriteIntValue("maxStayArrival", MaxStayArrival);
            writer.WriteStringValue("minAdvanceRes", MinAdvanceRes);
            writer.WriteIntValue("minStay", MinStay);
            writer.WriteIntValue("minStayArrival", MinStayArrival);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
