// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Repull.SDK.Models
{
    /// <summary>`request` — you stated it. `rate_plan` — Booking.com&apos;s maximum occupancy for this rate plan. `room` — Booking.com&apos;s room definition, used when the rate plan did not state one.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BookingRateWriteOccupancy_source
    {
        [EnumMember(Value = "request")]
        #pragma warning disable CS1591
        Request,
        #pragma warning restore CS1591
        [EnumMember(Value = "rate_plan")]
        #pragma warning disable CS1591
        Rate_plan,
        #pragma warning restore CS1591
        [EnumMember(Value = "room")]
        #pragma warning disable CS1591
        Room,
        #pragma warning restore CS1591
    }
}
