// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Repull.SDK.Models
{
    /// <summary>`unlist` closes the room&apos;s availability across the whole forward window, so the property stops selling. `relist` re-syncs the real calendar: dates that are genuinely blocked (a reservation, an owner stay) stay blocked, and only the closure `unlist` wrote lifts. They are not mirror images, and that is deliberate.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BookingPropertyActionRequest_action
    {
        [EnumMember(Value = "unlist")]
        #pragma warning disable CS1591
        Unlist,
        #pragma warning restore CS1591
        [EnumMember(Value = "relist")]
        #pragma warning disable CS1591
        Relist,
        #pragma warning restore CS1591
    }
}
