// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Repull.SDK.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BookingConnectRoomsResponse_missingCapabilities
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "content")]
        #pragma warning disable CS1591
        Content,
        #pragma warning restore CS1591
        [EnumMember(Value = "reservations")]
        #pragma warning disable CS1591
        Reservations,
        #pragma warning restore CS1591
        [EnumMember(Value = "rates")]
        #pragma warning disable CS1591
        Rates,
        #pragma warning restore CS1591
        [EnumMember(Value = "messaging")]
        #pragma warning disable CS1591
        Messaging,
        #pragma warning restore CS1591
    }
}
