// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.Models
{
    /// <summary>
    /// Same shape as `ListingPricingStrategy` minus the read-only fields. Send only fields you want to change.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListingPricingStrategyInput : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The compAdjustPct property</summary>
        public double? CompAdjustPct { get; set; }
        /// <summary>The compPositionTarget property</summary>
        public global::Repull.SDK.Models.ListingPricingStrategyInput_compPositionTarget? CompPositionTarget { get; set; }
        /// <summary>The dayOfWeekMultipliers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Repull.SDK.Models.ListingPricingStrategyInput_dayOfWeekMultipliers? DayOfWeekMultipliers { get; set; }
#nullable restore
#else
        public global::Repull.SDK.Models.ListingPricingStrategyInput_dayOfWeekMultipliers DayOfWeekMultipliers { get; set; }
#endif
        /// <summary>The eventBoostEnabled property</summary>
        public bool? EventBoostEnabled { get; set; }
        /// <summary>The eventBoostMaxPct property</summary>
        public double? EventBoostMaxPct { get; set; }
        /// <summary>The maxDailyChangePct property</summary>
        public double? MaxDailyChangePct { get; set; }
        /// <summary>The maxPrice property</summary>
        public double? MaxPrice { get; set; }
        /// <summary>The minPrice property</summary>
        public double? MinPrice { get; set; }
        /// <summary>The mode property</summary>
        public global::Repull.SDK.Models.ListingPricingStrategyInput_mode? Mode { get; set; }
        /// <summary>The ownerMinMonthlyPayout property</summary>
        public double? OwnerMinMonthlyPayout { get; set; }
        /// <summary>The targetMonthlyRevenue property</summary>
        public double? TargetMonthlyRevenue { get; set; }
        /// <summary>The targetOccupancyPct property</summary>
        public double? TargetOccupancyPct { get; set; }
        /// <summary>The weekendMarkupPct property</summary>
        public double? WeekendMarkupPct { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.Models.ListingPricingStrategyInput"/> and sets the default values.
        /// </summary>
        public ListingPricingStrategyInput()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.Models.ListingPricingStrategyInput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Repull.SDK.Models.ListingPricingStrategyInput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.Models.ListingPricingStrategyInput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "compAdjustPct", n => { CompAdjustPct = n.GetDoubleValue(); } },
                { "compPositionTarget", n => { CompPositionTarget = n.GetEnumValue<global::Repull.SDK.Models.ListingPricingStrategyInput_compPositionTarget>(); } },
                { "dayOfWeekMultipliers", n => { DayOfWeekMultipliers = n.GetObjectValue<global::Repull.SDK.Models.ListingPricingStrategyInput_dayOfWeekMultipliers>(global::Repull.SDK.Models.ListingPricingStrategyInput_dayOfWeekMultipliers.CreateFromDiscriminatorValue); } },
                { "eventBoostEnabled", n => { EventBoostEnabled = n.GetBoolValue(); } },
                { "eventBoostMaxPct", n => { EventBoostMaxPct = n.GetDoubleValue(); } },
                { "maxDailyChangePct", n => { MaxDailyChangePct = n.GetDoubleValue(); } },
                { "maxPrice", n => { MaxPrice = n.GetDoubleValue(); } },
                { "minPrice", n => { MinPrice = n.GetDoubleValue(); } },
                { "mode", n => { Mode = n.GetEnumValue<global::Repull.SDK.Models.ListingPricingStrategyInput_mode>(); } },
                { "ownerMinMonthlyPayout", n => { OwnerMinMonthlyPayout = n.GetDoubleValue(); } },
                { "targetMonthlyRevenue", n => { TargetMonthlyRevenue = n.GetDoubleValue(); } },
                { "targetOccupancyPct", n => { TargetOccupancyPct = n.GetDoubleValue(); } },
                { "weekendMarkupPct", n => { WeekendMarkupPct = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("compAdjustPct", CompAdjustPct);
            writer.WriteEnumValue<global::Repull.SDK.Models.ListingPricingStrategyInput_compPositionTarget>("compPositionTarget", CompPositionTarget);
            writer.WriteObjectValue<global::Repull.SDK.Models.ListingPricingStrategyInput_dayOfWeekMultipliers>("dayOfWeekMultipliers", DayOfWeekMultipliers);
            writer.WriteBoolValue("eventBoostEnabled", EventBoostEnabled);
            writer.WriteDoubleValue("eventBoostMaxPct", EventBoostMaxPct);
            writer.WriteDoubleValue("maxDailyChangePct", MaxDailyChangePct);
            writer.WriteDoubleValue("maxPrice", MaxPrice);
            writer.WriteDoubleValue("minPrice", MinPrice);
            writer.WriteEnumValue<global::Repull.SDK.Models.ListingPricingStrategyInput_mode>("mode", Mode);
            writer.WriteDoubleValue("ownerMinMonthlyPayout", OwnerMinMonthlyPayout);
            writer.WriteDoubleValue("targetMonthlyRevenue", TargetMonthlyRevenue);
            writer.WriteDoubleValue("targetOccupancyPct", TargetOccupancyPct);
            writer.WriteDoubleValue("weekendMarkupPct", WeekendMarkupPct);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
