// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.Models
{
    /// <summary>
    /// A short-lived signed upload target. PUT the raw file bytes to `uploadUrl` — the bytes never pass through the Repull API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListingPhotoUploadUrlResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Seconds until `uploadUrl` expires. Mint a new one via a fresh POST if the upload did not happen in time.</summary>
        public int? ExpiresIn { get; set; }
        /// <summary>The listingId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ListingId { get; set; }
#nullable restore
#else
        public string ListingId { get; set; }
#endif
        /// <summary>Storage path the photo will live at once uploaded. Pass this to `DELETE /v1/listings/{id}/photos` to remove it later.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>Durable public URL for the photo once the upload completes. Attach it to the listing via `PUT /v1/listings/{id}/content` (`photos` field).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublicUrl { get; set; }
#nullable restore
#else
        public string PublicUrl { get; set; }
#endif
        /// <summary>Opaque upload token bound to this signed URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Token { get; set; }
#nullable restore
#else
        public string Token { get; set; }
#endif
        /// <summary>PUT the raw file bytes here directly from the client. Not a Repull or vanio API endpoint — a signed storage URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UploadUrl { get; set; }
#nullable restore
#else
        public string UploadUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.Models.ListingPhotoUploadUrlResponse"/> and sets the default values.
        /// </summary>
        public ListingPhotoUploadUrlResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.Models.ListingPhotoUploadUrlResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Repull.SDK.Models.ListingPhotoUploadUrlResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.Models.ListingPhotoUploadUrlResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "expiresIn", n => { ExpiresIn = n.GetIntValue(); } },
                { "listingId", n => { ListingId = n.GetStringValue(); } },
                { "path", n => { Path = n.GetStringValue(); } },
                { "publicUrl", n => { PublicUrl = n.GetStringValue(); } },
                { "token", n => { Token = n.GetStringValue(); } },
                { "uploadUrl", n => { UploadUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("expiresIn", ExpiresIn);
            writer.WriteStringValue("listingId", ListingId);
            writer.WriteStringValue("path", Path);
            writer.WriteStringValue("publicUrl", PublicUrl);
            writer.WriteStringValue("token", Token);
            writer.WriteStringValue("uploadUrl", UploadUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
