// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Repull.SDK.Models
{
    /// <summary>The event name. This field is `event`, not `type`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ListingDeletedEvent_event
    {
        [EnumMember(Value = "listing.deleted")]
        #pragma warning disable CS1591
        ListingDeleted,
        #pragma warning restore CS1591
    }
}
