// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Repull.SDK.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListingUpdatedEvent_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "listing.updated")]
        #pragma warning disable CS1591
        ListingUpdated,
        #pragma warning restore CS1591
    }
}
