// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Repull.SDK.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListingSegment_qualityTier
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "budget")]
        #pragma warning disable CS1591
        Budget,
        #pragma warning restore CS1591
        [EnumMember(Value = "standard")]
        #pragma warning disable CS1591
        Standard,
        #pragma warning restore CS1591
        [EnumMember(Value = "upscale")]
        #pragma warning disable CS1591
        Upscale,
        #pragma warning restore CS1591
        [EnumMember(Value = "luxury")]
        #pragma warning disable CS1591
        Luxury,
        #pragma warning restore CS1591
    }
}
