// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Repull.SDK.Models
{
    /// <summary>Stable identifier for the recommendation kind. SDKs can switch on this safely.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ListingSegmentRecommendation_kind
    {
        [EnumMember(Value = "low_dna_coverage")]
        #pragma warning disable CS1591
        Low_dna_coverage,
        #pragma warning restore CS1591
        [EnumMember(Value = "self_not_scored")]
        #pragma warning disable CS1591
        Self_not_scored,
        #pragma warning restore CS1591
        [EnumMember(Value = "my_segment")]
        #pragma warning disable CS1591
        My_segment,
        #pragma warning restore CS1591
        [EnumMember(Value = "tier_uplift")]
        #pragma warning disable CS1591
        Tier_uplift,
        #pragma warning restore CS1591
        [EnumMember(Value = "segment_not_found")]
        #pragma warning disable CS1591
        Segment_not_found,
        #pragma warning restore CS1591
        [EnumMember(Value = "no_market_signal")]
        #pragma warning disable CS1591
        No_market_signal,
        #pragma warning restore CS1591
        [EnumMember(Value = "no_geo")]
        #pragma warning disable CS1591
        No_geo,
        #pragma warning restore CS1591
    }
}
