// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.Models
{
    /// <summary>
    /// Inputs for `POST /v1/listings`.**Address requirements — read this before you build the payload.** Publishing to Airbnb runs a create preflight that refuses the listing outright if the address is incomplete, and the refusal only surfaces later, at publish time. Airbnb requires `street` and `city` for every country. For a **US** property it additionally requires `state` and `postalCode`. Crucially, **omitting `countryCode` makes the listing behave as US**, so a listing created without a country needs `state` and `postalCode` too. Send `countryCode` explicitly for a non-US property. `lat`/`lng` alone are not enough — Airbnb rejects coordinates that are not backed by a full postal address. Use `GET /v1/listings/{id}/publish-status` to see which parts are still missing before you attempt a publish.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListingCreateRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The allowsChildren property</summary>
        public bool? AllowsChildren { get; set; }
        /// <summary>The allowsEvents property</summary>
        public bool? AllowsEvents { get; set; }
        /// <summary>The allowsPets property</summary>
        public bool? AllowsPets { get; set; }
        /// <summary>The allowsSmoking property</summary>
        public bool? AllowsSmoking { get; set; }
        /// <summary>The bathrooms property</summary>
        public double? Bathrooms { get; set; }
        /// <summary>The bedrooms property</summary>
        public int? Bedrooms { get; set; }
        /// <summary>The beds property</summary>
        public int? Beds { get; set; }
        /// <summary>The cancellationPolicy property</summary>
        public global::Repull.SDK.Models.ListingCreateRequest_cancellationPolicy? CancellationPolicy { get; set; }
        /// <summary>The checkInTimeStart property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CheckInTimeStart { get; set; }
#nullable restore
#else
        public string CheckInTimeStart { get; set; }
#endif
        /// <summary>The checkOutTime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CheckOutTime { get; set; }
#nullable restore
#else
        public string CheckOutTime { get; set; }
#endif
        /// <summary>City / town. Required by Airbnb for every country — a publish is refused without it.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? City { get; set; }
#nullable restore
#else
        public string City { get; set; }
#endif
        /// <summary>The cleaningFee property</summary>
        public double? CleaningFee { get; set; }
        /// <summary>ISO-3166 alpha-2 country code. **Send this for any non-US property.** Omitting it does not mean &quot;unknown&quot; — the publish path treats a listing with no country as US, which then requires `state` and `postalCode` and will refuse the listing when they are absent.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CountryCode { get; set; }
#nullable restore
#else
        public string CountryCode { get; set; }
#endif
        /// <summary>Nightly rate for every night that is not a weekend night. Stating it is what gives the new listing a calendar: 365 nights are written from it, and that calendar is what a publish sends to the channel. Without a price the listing has no availability to publish, which Booking.com refuses with &quot;No availability pushed&quot;.</summary>
        public double? DefaultDailyPrice { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Latitude. Useful for map search, but never a substitute for the postal address — Airbnb rejects coordinates it cannot reconcile with a full address.</summary>
        public double? Lat { get; set; }
        /// <summary>Longitude. See `lat`.</summary>
        public double? Lng { get; set; }
        /// <summary>Public guest-facing title</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The personCapacity property</summary>
        public int? PersonCapacity { get; set; }
        /// <summary>Postal code — ZIP in the US, postcode in the UK, and so on. **Required for a US property**, and a listing with no `countryCode` counts as US. Send the complete code: Booking.com rejects a partial postcode such as `SW6` where the full value is `SW6 1EP`. Alias: `zipcode`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PostalCode { get; set; }
#nullable restore
#else
        public string PostalCode { get; set; }
#endif
        /// <summary>Charged per guest above the number included in the nightly rate.</summary>
        public double? PricePerExtraGuest { get; set; }
        /// <summary>The propertyType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PropertyType { get; set; }
#nullable restore
#else
        public string PropertyType { get; set; }
#endif
        /// <summary>Airbnb&apos;s finer property-type category, when you know it. Optional.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PropertyTypeCategory { get; set; }
#nullable restore
#else
        public string PropertyTypeCategory { get; set; }
#endif
        /// <summary>What the guest actually gets. Airbnb refuses to activate a listing that has not stated one, answering &quot;Please specify a valid room type&quot; — which reads like a beds problem and is not. It is never defaulted: most listings are an entire home, but hundreds are a private or hotel room, and publishing one of those as an entire home is a false claim about someone&apos;s property. Settable later with `PUT /v1/listings/{id}/content` under `details`.</summary>
        public global::Repull.SDK.Models.ListingCreateRequest_roomTypeCategory? RoomTypeCategory { get; set; }
        /// <summary>State, province or region. **Required for a US property**, and a listing with no `countryCode` counts as US. Optional elsewhere, but stored and used wherever the channel carries it.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>Street address including the number. Required by Airbnb for every country — a publish is refused without it.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Street { get; set; }
#nullable restore
#else
        public string Street { get; set; }
#endif
        /// <summary>The summary property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Summary { get; set; }
#nullable restore
#else
        public string Summary { get; set; }
#endif
        /// <summary>Nightly rate for Saturday and Sunday nights (UTC). Omit it and those nights take `defaultDailyPrice`. It is the same rate the direct-booking quoter charges for a weekend night, so the calendar and a quote cannot disagree.</summary>
        public double? WeekendPrice { get; set; }
        /// <summary>Alias for `postalCode`, accepted because it is the field name on the Airbnb mirror. `postalCode` wins if you send both. Prefer `postalCode` — the field holds non-US postcodes too.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Zipcode { get; set; }
#nullable restore
#else
        public string Zipcode { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.Models.ListingCreateRequest"/> and sets the default values.
        /// </summary>
        public ListingCreateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.Models.ListingCreateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Repull.SDK.Models.ListingCreateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.Models.ListingCreateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowsChildren", n => { AllowsChildren = n.GetBoolValue(); } },
                { "allowsEvents", n => { AllowsEvents = n.GetBoolValue(); } },
                { "allowsPets", n => { AllowsPets = n.GetBoolValue(); } },
                { "allowsSmoking", n => { AllowsSmoking = n.GetBoolValue(); } },
                { "bathrooms", n => { Bathrooms = n.GetDoubleValue(); } },
                { "bedrooms", n => { Bedrooms = n.GetIntValue(); } },
                { "beds", n => { Beds = n.GetIntValue(); } },
                { "cancellationPolicy", n => { CancellationPolicy = n.GetEnumValue<global::Repull.SDK.Models.ListingCreateRequest_cancellationPolicy>(); } },
                { "checkInTimeStart", n => { CheckInTimeStart = n.GetStringValue(); } },
                { "checkOutTime", n => { CheckOutTime = n.GetStringValue(); } },
                { "city", n => { City = n.GetStringValue(); } },
                { "cleaningFee", n => { CleaningFee = n.GetDoubleValue(); } },
                { "countryCode", n => { CountryCode = n.GetStringValue(); } },
                { "defaultDailyPrice", n => { DefaultDailyPrice = n.GetDoubleValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "lat", n => { Lat = n.GetDoubleValue(); } },
                { "lng", n => { Lng = n.GetDoubleValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "personCapacity", n => { PersonCapacity = n.GetIntValue(); } },
                { "postalCode", n => { PostalCode = n.GetStringValue(); } },
                { "pricePerExtraGuest", n => { PricePerExtraGuest = n.GetDoubleValue(); } },
                { "propertyType", n => { PropertyType = n.GetStringValue(); } },
                { "propertyTypeCategory", n => { PropertyTypeCategory = n.GetStringValue(); } },
                { "roomTypeCategory", n => { RoomTypeCategory = n.GetEnumValue<global::Repull.SDK.Models.ListingCreateRequest_roomTypeCategory>(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "street", n => { Street = n.GetStringValue(); } },
                { "summary", n => { Summary = n.GetStringValue(); } },
                { "weekendPrice", n => { WeekendPrice = n.GetDoubleValue(); } },
                { "zipcode", n => { Zipcode = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allowsChildren", AllowsChildren);
            writer.WriteBoolValue("allowsEvents", AllowsEvents);
            writer.WriteBoolValue("allowsPets", AllowsPets);
            writer.WriteBoolValue("allowsSmoking", AllowsSmoking);
            writer.WriteDoubleValue("bathrooms", Bathrooms);
            writer.WriteIntValue("bedrooms", Bedrooms);
            writer.WriteIntValue("beds", Beds);
            writer.WriteEnumValue<global::Repull.SDK.Models.ListingCreateRequest_cancellationPolicy>("cancellationPolicy", CancellationPolicy);
            writer.WriteStringValue("checkInTimeStart", CheckInTimeStart);
            writer.WriteStringValue("checkOutTime", CheckOutTime);
            writer.WriteStringValue("city", City);
            writer.WriteDoubleValue("cleaningFee", CleaningFee);
            writer.WriteStringValue("countryCode", CountryCode);
            writer.WriteDoubleValue("defaultDailyPrice", DefaultDailyPrice);
            writer.WriteStringValue("description", Description);
            writer.WriteDoubleValue("lat", Lat);
            writer.WriteDoubleValue("lng", Lng);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("personCapacity", PersonCapacity);
            writer.WriteStringValue("postalCode", PostalCode);
            writer.WriteDoubleValue("pricePerExtraGuest", PricePerExtraGuest);
            writer.WriteStringValue("propertyType", PropertyType);
            writer.WriteStringValue("propertyTypeCategory", PropertyTypeCategory);
            writer.WriteEnumValue<global::Repull.SDK.Models.ListingCreateRequest_roomTypeCategory>("roomTypeCategory", RoomTypeCategory);
            writer.WriteStringValue("state", State);
            writer.WriteStringValue("street", Street);
            writer.WriteStringValue("summary", Summary);
            writer.WriteDoubleValue("weekendPrice", WeekendPrice);
            writer.WriteStringValue("zipcode", Zipcode);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
