// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MigrationReservationRef : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The checkIn property</summary>
        public Date? CheckIn { get; set; }
        /// <summary>The checkOut property</summary>
        public Date? CheckOut { get; set; }
        /// <summary>The confirmationCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConfirmationCode { get; set; }
#nullable restore
#else
        public string ConfirmationCode { get; set; }
#endif
        /// <summary>The platform property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Platform { get; set; }
#nullable restore
#else
        public string Platform { get; set; }
#endif
        /// <summary>The reservationId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReservationId { get; set; }
#nullable restore
#else
        public string ReservationId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.Models.MigrationReservationRef"/> and sets the default values.
        /// </summary>
        public MigrationReservationRef()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.Models.MigrationReservationRef"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Repull.SDK.Models.MigrationReservationRef CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.Models.MigrationReservationRef();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "checkIn", n => { CheckIn = n.GetDateValue(); } },
                { "checkOut", n => { CheckOut = n.GetDateValue(); } },
                { "confirmationCode", n => { ConfirmationCode = n.GetStringValue(); } },
                { "platform", n => { Platform = n.GetStringValue(); } },
                { "reservationId", n => { ReservationId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateValue("checkIn", CheckIn);
            writer.WriteDateValue("checkOut", CheckOut);
            writer.WriteStringValue("confirmationCode", ConfirmationCode);
            writer.WriteStringValue("platform", Platform);
            writer.WriteStringValue("reservationId", ReservationId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
