// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Repull.SDK.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PaymentCompletedEvent_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "payment.completed")]
        #pragma warning disable CS1591
        PaymentCompleted,
        #pragma warning restore CS1591
    }
}
