// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PmsWritePolicy_calendar : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Open and close nights. Off also means the PMS&apos;s bookings never block the calendar on other channels.</summary>
        public bool? Availability { get; set; }
        /// <summary>Nightly prices.</summary>
        public bool? Rates { get; set; }
        /// <summary>Minimum stay and other stay restrictions.</summary>
        public bool? Restrictions { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.Models.PmsWritePolicy_calendar"/> and sets the default values.
        /// </summary>
        public PmsWritePolicy_calendar()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.Models.PmsWritePolicy_calendar"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Repull.SDK.Models.PmsWritePolicy_calendar CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.Models.PmsWritePolicy_calendar();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "availability", n => { Availability = n.GetBoolValue(); } },
                { "rates", n => { Rates = n.GetBoolValue(); } },
                { "restrictions", n => { Restrictions = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("availability", Availability);
            writer.WriteBoolValue("rates", Rates);
            writer.WriteBoolValue("restrictions", Restrictions);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
