// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Quote_pricing : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cleaningFee property</summary>
        public double? CleaningFee { get; set; }
        /// <summary>The lengthOfStayDiscount property</summary>
        public double? LengthOfStayDiscount { get; set; }
        /// <summary>The lengthOfStayDiscountPercent property</summary>
        public double? LengthOfStayDiscountPercent { get; set; }
        /// <summary>The nightlyTotal property</summary>
        public double? NightlyTotal { get; set; }
        /// <summary>The otherFees property</summary>
        public double? OtherFees { get; set; }
        /// <summary>The petFee property</summary>
        public double? PetFee { get; set; }
        /// <summary>The taxes property</summary>
        public double? Taxes { get; set; }
        /// <summary>The total property</summary>
        public double? Total { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.Models.Quote_pricing"/> and sets the default values.
        /// </summary>
        public Quote_pricing()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.Models.Quote_pricing"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Repull.SDK.Models.Quote_pricing CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.Models.Quote_pricing();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cleaningFee", n => { CleaningFee = n.GetDoubleValue(); } },
                { "lengthOfStayDiscount", n => { LengthOfStayDiscount = n.GetDoubleValue(); } },
                { "lengthOfStayDiscountPercent", n => { LengthOfStayDiscountPercent = n.GetDoubleValue(); } },
                { "nightlyTotal", n => { NightlyTotal = n.GetDoubleValue(); } },
                { "otherFees", n => { OtherFees = n.GetDoubleValue(); } },
                { "petFee", n => { PetFee = n.GetDoubleValue(); } },
                { "taxes", n => { Taxes = n.GetDoubleValue(); } },
                { "total", n => { Total = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("cleaningFee", CleaningFee);
            writer.WriteDoubleValue("lengthOfStayDiscount", LengthOfStayDiscount);
            writer.WriteDoubleValue("lengthOfStayDiscountPercent", LengthOfStayDiscountPercent);
            writer.WriteDoubleValue("nightlyTotal", NightlyTotal);
            writer.WriteDoubleValue("otherFees", OtherFees);
            writer.WriteDoubleValue("petFee", PetFee);
            writer.WriteDoubleValue("taxes", Taxes);
            writer.WriteDoubleValue("total", Total);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
