// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.Models
{
    /// <summary>
    /// A booking/reservation from a connected PMS. Identical shape between list-row (`GET /v1/reservations`) and detail (`GET /v1/reservations/{id}`) — SDK consumers can use the same type for both.The canonical (post-2026-05) shape uses nested `primaryGuest`, `occupancy`, `financials` blocks. The legacy flat fields (`guestId`, `totalPrice`, `currency`, `guestDetails`) remain populated for back-compat and are marked `deprecated` here. New consumers should read from the nested blocks; existing consumers continue to work unchanged.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Reservation : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>When the booking was made on the source channel (when reported by the channel).</summary>
        public DateTimeOffset? BookedAt { get; set; }
        /// <summary>The checkIn property</summary>
        public Date? CheckIn { get; set; }
        /// <summary>Local check-in time for this stay, `HH:MM` on a 24-hour clock in the **property&apos;s own timezone** — not UTC. Usually inherited from the listing policy, overridden per reservation where an early check-in was agreed. `null` when unknown. This is the same field `PATCH /v1/reservations/{id}` writes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CheckInTime { get; set; }
#nullable restore
#else
        public string CheckInTime { get; set; }
#endif
        /// <summary>The checkOut property</summary>
        public Date? CheckOut { get; set; }
        /// <summary>Local check-out time for this stay, `HH:MM` on a 24-hour clock in the property&apos;s own timezone. Pair with `checkOut` to schedule the turnover clean. `null` when unknown. This is the same field `PATCH /v1/reservations/{id}` writes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CheckOutTime { get; set; }
#nullable restore
#else
        public string CheckOutTime { get; set; }
#endif
        /// <summary>Channel-side confirmation code (Airbnb HMxxx, Booking.com numeric, etc.).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConfirmationCode { get; set; }
#nullable restore
#else
        public string ConfirmationCode { get; set; }
#endif
        /// <summary>When the reservation row was created in Repull (not the booking-on-channel timestamp).</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>DEPRECATED — use `financials.currency`. ISO 4217 currency code.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>Normalized money block. Always populated for paid reservations.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Repull.SDK.Models.ReservationFinancials? Financials { get; set; }
#nullable restore
#else
        public global::Repull.SDK.Models.ReservationFinancials Financials { get; set; }
#endif
        /// <summary>DEPRECATED — use `occupancy` for normalized counts and `primaryGuest` for guest identity. Raw guest details from the source channel; shape varies by platform.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Repull.SDK.Models.Reservation_guestDetails? GuestDetails { get; set; }
#nullable restore
#else
        public global::Repull.SDK.Models.Reservation_guestDetails GuestDetails { get; set; }
#endif
        /// <summary>DEPRECATED — use `primaryGuest.id`. Internal Repull guest ID. Kept populated for back-compat.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GuestId { get; set; }
#nullable restore
#else
        public string GuestId { get; set; }
#endif
        /// <summary>Pre-resolved display name (`firstName lastName`) from the joined guest row. Undefined when no first name is available.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GuestName { get; set; }
#nullable restore
#else
        public string GuestName { get; set; }
#endif
        /// <summary>Internal Repull reservation ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Internal Repull listing ID this reservation is on.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ListingId { get; set; }
#nullable restore
#else
        public string ListingId { get; set; }
#endif
        /// <summary>Normalized guest counts. May be undefined when the source channel did not provide counts.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Repull.SDK.Models.ReservationOccupancy? Occupancy { get; set; }
#nullable restore
#else
        public global::Repull.SDK.Models.ReservationOccupancy Occupancy { get; set; }
#endif
        /// <summary>Why a `pending` reservation is pending — who has to act next. `host_approval`: a booking request the host must accept or decline (see `respondBy`). `guest_payment`: Airbnb is waiting for the guest to pay. `guest_verification`: Airbnb is holding the booking while the guest completes identity verification. The last two need no action from the host, and Airbnb does not publish a deadline for them. Present only while `status` is `pending`; when it changes you receive `reservation.updated` with the previous raw status in `previousAttributes.status`, even if `status` stays `pending`.</summary>
        public global::Repull.SDK.Models.Reservation_pendingReason? PendingReason { get; set; }
        /// <summary>DEPRECATED alias for `source`. Same value, kept for back-compat.</summary>
        [Obsolete("")]
        public global::Repull.SDK.Models.Reservation_platform? Platform { get; set; }
        /// <summary>Inline guest summary. May be undefined for owner-blocks / pre-arrival rows.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Repull.SDK.Models.ReservationPrimaryGuest? PrimaryGuest { get; set; }
#nullable restore
#else
        public global::Repull.SDK.Models.ReservationPrimaryGuest PrimaryGuest { get; set; }
#endif
        /// <summary>On a `pending` Airbnb booking request (`pendingReason: host_approval`) that can still be answered: when it lapses (24 hours after the guest asked). Accept or decline before then with `POST /v1/reservations/{id}/accept` / `/decline`. Absent on every other reservation, including bookings Airbnb is holding for the guest&apos;s payment or verification — those have no deadline we can report.</summary>
        public DateTimeOffset? RespondBy { get; set; }
        /// <summary>Booking source / channel. Lowercase. May be null on legacy rows. Canonical name as of 2026-05; `platform` is kept as an alias.</summary>
        public global::Repull.SDK.Models.Reservation_source? Source { get; set; }
        /// <summary>Lifecycle status. The API normalises a multi-decade internal taxonomy down to these four buckets, so the value you receive is always one of the enum constants. `completed` is derived from `checkOut &lt; today`. A `pending` booking request the channel already let lapse — Airbnb expires an unanswered request 24 hours after the guest asks, and no request can be answered once its check-in has passed — is reported as `cancelled` with `statusDetail: &quot;request_expired&quot;`, even when the channel never told us. Every `cancelled` reservation says how it ended in `statusDetail` when the channel tells us.</summary>
        public global::Repull.SDK.Models.Reservation_status? Status { get; set; }
        /// <summary>On a `cancelled` reservation: how it ended. `request_expired` — a booking request nobody answered in time (Airbnb&apos;s 24-hour window passed, or the check-in did), whether the channel reported it or we derived it. `declined` — the host declined the request. `request_voided` — the request was withdrawn or voided before anyone answered it. `verification_failed` — the guest failed Airbnb&apos;s identity verification. `hold_voided` — Airbnb voided a booking it was holding for the guest&apos;s payment or verification. `cancelled_by_guest` / `cancelled_by_host` / `cancelled_by_platform` — a booking cancelled by that party (`platform` is the channel itself, e.g. Airbnb support). Matches what the webhooks report for the same change. Absent on every other status, and on a cancellation whose channel gives no reason.</summary>
        public global::Repull.SDK.Models.Reservation_statusDetail? StatusDetail { get; set; }
        /// <summary>DEPRECATED — use `financials.totalPrice` (a number). Decimal-as-string (precision 10, scale 2) kept for back-compat.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalPrice { get; set; }
#nullable restore
#else
        public string TotalPrice { get; set; }
#endif
        /// <summary>Last time this reservation was modified (dates, status, price, or guest details). Advances on every amendment or cancellation — poll or compare this value to reconcile changes instead of fingerprinting individual fields.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.Models.Reservation"/> and sets the default values.
        /// </summary>
        public Reservation()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.Models.Reservation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Repull.SDK.Models.Reservation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.Models.Reservation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bookedAt", n => { BookedAt = n.GetDateTimeOffsetValue(); } },
                { "checkIn", n => { CheckIn = n.GetDateValue(); } },
                { "checkInTime", n => { CheckInTime = n.GetStringValue(); } },
                { "checkOut", n => { CheckOut = n.GetDateValue(); } },
                { "checkOutTime", n => { CheckOutTime = n.GetStringValue(); } },
                { "confirmationCode", n => { ConfirmationCode = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "financials", n => { Financials = n.GetObjectValue<global::Repull.SDK.Models.ReservationFinancials>(global::Repull.SDK.Models.ReservationFinancials.CreateFromDiscriminatorValue); } },
                { "guestDetails", n => { GuestDetails = n.GetObjectValue<global::Repull.SDK.Models.Reservation_guestDetails>(global::Repull.SDK.Models.Reservation_guestDetails.CreateFromDiscriminatorValue); } },
                { "guestId", n => { GuestId = n.GetStringValue(); } },
                { "guestName", n => { GuestName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "listingId", n => { ListingId = n.GetStringValue(); } },
                { "occupancy", n => { Occupancy = n.GetObjectValue<global::Repull.SDK.Models.ReservationOccupancy>(global::Repull.SDK.Models.ReservationOccupancy.CreateFromDiscriminatorValue); } },
                { "pendingReason", n => { PendingReason = n.GetEnumValue<global::Repull.SDK.Models.Reservation_pendingReason>(); } },
                { "platform", n => { Platform = n.GetEnumValue<global::Repull.SDK.Models.Reservation_platform>(); } },
                { "primaryGuest", n => { PrimaryGuest = n.GetObjectValue<global::Repull.SDK.Models.ReservationPrimaryGuest>(global::Repull.SDK.Models.ReservationPrimaryGuest.CreateFromDiscriminatorValue); } },
                { "respondBy", n => { RespondBy = n.GetDateTimeOffsetValue(); } },
                { "source", n => { Source = n.GetEnumValue<global::Repull.SDK.Models.Reservation_source>(); } },
                { "status", n => { Status = n.GetEnumValue<global::Repull.SDK.Models.Reservation_status>(); } },
                { "statusDetail", n => { StatusDetail = n.GetEnumValue<global::Repull.SDK.Models.Reservation_statusDetail>(); } },
                { "totalPrice", n => { TotalPrice = n.GetStringValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("bookedAt", BookedAt);
            writer.WriteDateValue("checkIn", CheckIn);
            writer.WriteStringValue("checkInTime", CheckInTime);
            writer.WriteDateValue("checkOut", CheckOut);
            writer.WriteStringValue("checkOutTime", CheckOutTime);
            writer.WriteStringValue("confirmationCode", ConfirmationCode);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("currency", Currency);
            writer.WriteObjectValue<global::Repull.SDK.Models.ReservationFinancials>("financials", Financials);
            writer.WriteObjectValue<global::Repull.SDK.Models.Reservation_guestDetails>("guestDetails", GuestDetails);
            writer.WriteStringValue("guestId", GuestId);
            writer.WriteStringValue("guestName", GuestName);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("listingId", ListingId);
            writer.WriteObjectValue<global::Repull.SDK.Models.ReservationOccupancy>("occupancy", Occupancy);
            writer.WriteEnumValue<global::Repull.SDK.Models.Reservation_pendingReason>("pendingReason", PendingReason);
            writer.WriteEnumValue<global::Repull.SDK.Models.Reservation_platform>("platform", Platform);
            writer.WriteObjectValue<global::Repull.SDK.Models.ReservationPrimaryGuest>("primaryGuest", PrimaryGuest);
            writer.WriteDateTimeOffsetValue("respondBy", RespondBy);
            writer.WriteEnumValue<global::Repull.SDK.Models.Reservation_source>("source", Source);
            writer.WriteEnumValue<global::Repull.SDK.Models.Reservation_status>("status", Status);
            writer.WriteEnumValue<global::Repull.SDK.Models.Reservation_statusDetail>("statusDetail", StatusDetail);
            writer.WriteStringValue("totalPrice", TotalPrice);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
