// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Repull.SDK.Models
{
    /// <summary>Why a `pending` reservation is pending — who has to act next. `host_approval`: a booking request the host must accept or decline (see `respondBy`). `guest_payment`: Airbnb is waiting for the guest to pay. `guest_verification`: Airbnb is holding the booking while the guest completes identity verification. The last two need no action from the host, and Airbnb does not publish a deadline for them. Present only while `status` is `pending`; when it changes you receive `reservation.updated` with the previous raw status in `previousAttributes.status`, even if `status` stays `pending`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Reservation_pendingReason
    {
        [EnumMember(Value = "host_approval")]
        #pragma warning disable CS1591
        Host_approval,
        #pragma warning restore CS1591
        [EnumMember(Value = "guest_payment")]
        #pragma warning disable CS1591
        Guest_payment,
        #pragma warning restore CS1591
        [EnumMember(Value = "guest_verification")]
        #pragma warning disable CS1591
        Guest_verification,
        #pragma warning restore CS1591
    }
}
