// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.Models
{
    /// <summary>
    /// Lightweight review snapshot delivered as `data.object` on `review.*` events. Fetch the full review (category ratings, public text, private feedback, response body) via `GET /v1/reviews/{id}`.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReviewWebhookObject : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Source channel the review came from.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Channel { get; set; }
#nullable restore
#else
        public string Channel { get; set; }
#endif
        /// <summary>Workspace (customer) id.</summary>
        public int? CustomerId { get; set; }
        /// <summary>Repull-internal review id. Pass to `GET /v1/reviews/{id}`.</summary>
        public int? Id { get; set; }
        /// <summary>Repull listing id the review is about.</summary>
        public int? ListingId { get; set; }
        /// <summary>Overall star rating, if present.</summary>
        public int? Rating { get; set; }
        /// <summary>Repull reservation id the review is attached to, if known.</summary>
        public int? ReservationId { get; set; }
        /// <summary>Who wrote the review — `guest` (about the host/property) or `host` (about the guest).</summary>
        public global::Repull.SDK.Models.ReviewWebhookObject_reviewerRole? ReviewerRole { get; set; }
        /// <summary>When the review was submitted on the source channel.</summary>
        public DateTimeOffset? SubmittedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.Models.ReviewWebhookObject"/> and sets the default values.
        /// </summary>
        public ReviewWebhookObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.Models.ReviewWebhookObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Repull.SDK.Models.ReviewWebhookObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.Models.ReviewWebhookObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "channel", n => { Channel = n.GetStringValue(); } },
                { "customerId", n => { CustomerId = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "listingId", n => { ListingId = n.GetIntValue(); } },
                { "rating", n => { Rating = n.GetIntValue(); } },
                { "reservationId", n => { ReservationId = n.GetIntValue(); } },
                { "reviewerRole", n => { ReviewerRole = n.GetEnumValue<global::Repull.SDK.Models.ReviewWebhookObject_reviewerRole>(); } },
                { "submittedAt", n => { SubmittedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("channel", Channel);
            writer.WriteIntValue("customerId", CustomerId);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("listingId", ListingId);
            writer.WriteIntValue("rating", Rating);
            writer.WriteIntValue("reservationId", ReservationId);
            writer.WriteEnumValue<global::Repull.SDK.Models.ReviewWebhookObject_reviewerRole>("reviewerRole", ReviewerRole);
            writer.WriteDateTimeOffsetValue("submittedAt", SubmittedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
