// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Repull.SDK.Models
{
    /// <summary>Which quota this warning is about.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UsageQuotaWarningPayload_scope
    {
        [EnumMember(Value = "daily_requests")]
        #pragma warning disable CS1591
        Daily_requests,
        #pragma warning restore CS1591
    }
}
