// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.Models
{
    /// <summary>
    /// Where a Vrbo account import stands. Nothing is imported until its unit mapping is confirmed; then upcoming bookings and the last 30 days of messages come first, and the whole account history after.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VrboImportStatus : IAdditionalDataHolder, IParsable
    {
        /// <summary>`messaging`: bookings and messages only, the calendar is never pushed.</summary>
        public global::Repull.SDK.Models.VrboImportStatus_accessType? AccessType { get; set; }
        /// <summary>The accountId property</summary>
        public int? AccountId { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The conversationsImported property</summary>
        public int? ConversationsImported { get; set; }
        /// <summary>The conversationsSeen property</summary>
        public int? ConversationsSeen { get; set; }
        /// <summary>The whole account history is imported.</summary>
        public bool? HistoryComplete { get; set; }
        /// <summary>The historyCompletedAt property</summary>
        public DateTimeOffset? HistoryCompletedAt { get; set; }
        /// <summary>Last completed sync (Vrbo is read every few minutes and on each Vrbo notification email).</summary>
        public DateTimeOffset? LastSyncedAt { get; set; }
        /// <summary>Upcoming bookings and the last 30 days are in.</summary>
        public DateTimeOffset? PriorityImportedAt { get; set; }
        /// <summary>When the mapping was confirmed.</summary>
        public DateTimeOffset? RequestedAt { get; set; }
        /// <summary>Bookings imported so far.</summary>
        public int? Reservations { get; set; }
        /// <summary>The state property</summary>
        public global::Repull.SDK.Models.VrboImportStatus_state? State { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.Models.VrboImportStatus"/> and sets the default values.
        /// </summary>
        public VrboImportStatus()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.Models.VrboImportStatus"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Repull.SDK.Models.VrboImportStatus CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.Models.VrboImportStatus();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accessType", n => { AccessType = n.GetEnumValue<global::Repull.SDK.Models.VrboImportStatus_accessType>(); } },
                { "accountId", n => { AccountId = n.GetIntValue(); } },
                { "conversationsImported", n => { ConversationsImported = n.GetIntValue(); } },
                { "conversationsSeen", n => { ConversationsSeen = n.GetIntValue(); } },
                { "historyComplete", n => { HistoryComplete = n.GetBoolValue(); } },
                { "historyCompletedAt", n => { HistoryCompletedAt = n.GetDateTimeOffsetValue(); } },
                { "lastSyncedAt", n => { LastSyncedAt = n.GetDateTimeOffsetValue(); } },
                { "priorityImportedAt", n => { PriorityImportedAt = n.GetDateTimeOffsetValue(); } },
                { "requestedAt", n => { RequestedAt = n.GetDateTimeOffsetValue(); } },
                { "reservations", n => { Reservations = n.GetIntValue(); } },
                { "state", n => { State = n.GetEnumValue<global::Repull.SDK.Models.VrboImportStatus_state>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Repull.SDK.Models.VrboImportStatus_accessType>("accessType", AccessType);
            writer.WriteIntValue("accountId", AccountId);
            writer.WriteIntValue("conversationsImported", ConversationsImported);
            writer.WriteIntValue("conversationsSeen", ConversationsSeen);
            writer.WriteBoolValue("historyComplete", HistoryComplete);
            writer.WriteDateTimeOffsetValue("historyCompletedAt", HistoryCompletedAt);
            writer.WriteDateTimeOffsetValue("lastSyncedAt", LastSyncedAt);
            writer.WriteDateTimeOffsetValue("priorityImportedAt", PriorityImportedAt);
            writer.WriteDateTimeOffsetValue("requestedAt", RequestedAt);
            writer.WriteIntValue("reservations", Reservations);
            writer.WriteEnumValue<global::Repull.SDK.Models.VrboImportStatus_state>("state", State);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
