// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Repull.SDK.Models
{
    /// <summary>
    /// Canonical catalog of every event the API can deliver, grouped by domain. Each entry includes a realistic `samplePayload` matching the discriminated `WebhookEvent` union — so SDKs can render docs and dashboards from this single source of truth.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebhookEventCatalog : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The domains property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Repull.SDK.Models.WebhookEventCatalog_domains>? Domains { get; set; }
#nullable restore
#else
        public List<global::Repull.SDK.Models.WebhookEventCatalog_domains> Domains { get; set; }
#endif
        /// <summary>All events in a flat list (same entries as `domains[].events`, ungrouped).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Repull.SDK.Models.WebhookEventCatalogEntry>? Flat { get; set; }
#nullable restore
#else
        public List<global::Repull.SDK.Models.WebhookEventCatalogEntry> Flat { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Repull.SDK.Models.WebhookEventCatalog"/> and sets the default values.
        /// </summary>
        public WebhookEventCatalog()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Repull.SDK.Models.WebhookEventCatalog"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Repull.SDK.Models.WebhookEventCatalog CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Repull.SDK.Models.WebhookEventCatalog();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "domains", n => { Domains = n.GetCollectionOfObjectValues<global::Repull.SDK.Models.WebhookEventCatalog_domains>(global::Repull.SDK.Models.WebhookEventCatalog_domains.CreateFromDiscriminatorValue)?.AsList(); } },
                { "flat", n => { Flat = n.GetCollectionOfObjectValues<global::Repull.SDK.Models.WebhookEventCatalogEntry>(global::Repull.SDK.Models.WebhookEventCatalogEntry.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Repull.SDK.Models.WebhookEventCatalog_domains>("domains", Domains);
            writer.WriteCollectionOfObjectValues<global::Repull.SDK.Models.WebhookEventCatalogEntry>("flat", Flat);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
